version: '3'

services:
  nrf:
    build:
      context: .
      dockerfile: ./compose/Dockerfile
    volumes:
      - .:/app
    privileged: true
    network_mode: "host" #required for bluetooth access
    entrypoint: ["/app/compose/entry_point.sh"]
    command: ["badge_03v6_noDebug","flashAPP"]
