version: '3'

services:
  nrf:
    build:
      context: .
      dockerfile: ./compose/Dockerfile_raspi
    # Comment the volume setting if running on a remote machine using docker-machine
    # Also, uncomment the COPY app command at the end of the raspberry Dockerfile
    volumes:
      - .:/app
      - /dev/bus/usb:/dev/bus/usb #required for serial port access
    privileged: true
    entrypoint: ["/app/compose/entry_point.sh"]
    command: ["badge_03v6_noDebug","flashAPP"]
