//
// Created by Andrew Bartow on 1/27/17.
//

#ifndef OPENBADGE_BADGE_FS_PRIVATE_H
#define OPENBADGE_BADGE_FS_PRIVATE_H

/**
 * NOTE: THIS IS A PRIVATE FILE AND SHOULD ONLY BE INCLUDED FROM BADGE_FS.H. ALL OTHER CONSUMERS SHOULD USE BADGE_FS
 *  AND NOT THIS FILE DIRECTLY.
 */

#endif //OPENBADGE_BADGE_FS_PRIVATE_H
