/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.9.1 at Tue Sep  4 02:09:10 2018. */

#include "test.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t Message_fields[2] = {
    PB_FIELD(  1, UINT32  , OPTIONAL, STATIC  , FIRST, Message, test, test, 0),
    PB_LAST_FIELD
};


/* @@protoc_insertion_point(eof) */
