FROM resin/rpi-raspbian:stretch

MAINTAINER Oren Lederman <orenled@mit.edu>
# Based on https://github.com/FruityLoopers/fruityfactory

RUN apt-get update && apt-get install -y \
	build-essential \
  libbluetooth-dev \
  bluez \
  rfkill \
  bluetooth \
  unzip \
  binutils-avr \
  git \
  cmake \
  minicom screen \
  wget \ 
  gcc-arm-none-eabi \
  libnewlib-arm-none-eabi \
  vim



RUN mkdir -p /opt/downloads

WORKDIR /opt

# GCC ARM
# Installed with apt-get

# nRF SDK
ENV NRF_SDK_PATH=/opt/nrf/sdk/nrf_sdk_8_1
run mkdir -p $NRF_SDK_PATH
RUN wget https://developer.nordicsemi.com/nRF51_SDK/nRF51_SDK_v8.x.x/nRF51_SDK_8.1.0_b6ed55f.zip -O downloads/nRF51_SDK_8.1.0_b6ed55f.zip
RUN unzip -q downloads/nRF51_SDK_8.1.0_b6ed55f.zip -d $NRF_SDK_PATH

COPY compose/Makefile.posix_raspi $NRF_SDK_PATH/components/toolchain/gcc/Makefile.posix

# SEGGER
COPY compose/JLink_Linux_V616i_arm.tgz /opt/downloads/JLink_Linux_V616i_arm.tgz
RUN tar -C /opt/ -xzf downloads/JLink_Linux_V616i_arm.tgz
RUN ln -s /opt/JLink_Linux_V616i_arm/JLinkExe /usr/local/bin/JLinkExe

# Uncomment if running on a remote raspberry pi machine
#COPY .  /app

################################
## Bluetooth Python environment
################################
RUN apt-get update && apt-get install -y \
    python \
    python-dev \
    python-pip \
    python-setuptools \
    gcc \
    build-essential \
    libglib2.0-dev \
    bluez \
    --no-install-recommends && \
    rm -rf /var/lib/apt/lists/*

COPY ./requirements.txt /tmp/requirements.txt
RUN pip install -r /tmp/requirements.txt
